### PR TITLE
Add arm64 and armv7 to build targets for Docker image

### PR DESCRIPTION
**Pull request by tandy-1000**

### CODE REVIEW

**Comment by tchapi** [comment]
Out of curiosity, why `armv7`?

**Review by tchapi — APPROVED** [review]

**Comment by tandy-1000** [comment]
Why not? :) I won't use it but its what the RasPi 1 uses..

**Comment by tandy-1000** [comment]
Merge time?

**Comment by tchapi** [comment]
CI build time (and credits), yes. I'd rather wait for someone to _actively_ use the image. AMD and ARM in 64bit flavours should be sufficient for now

**Comment by tchapi** [comment]
Thanks!

**Comment by tandy-1000** [comment]
Thank you! Is there any way to trigger a new docker image build so I can test this?

**Comment by tchapi** [comment]
I'm building the `edge` tag right now (see [here](https://github.com/tchapi/davis/actions/runs/4428230900))

... but it fails: https://github.com/tchapi/davis/actions/runs/4428230900/jobs/7767001766

**Comment by tchapi** [comment]
Do you have time to look at it and find a solution? Maybe we need two distinct workflows (one for each platform)

**Comment by tandy-1000** [comment]
> Do you have time to look at it and find a solution? Maybe we need two distinct workflows (one for each platform)

Yep! Just opened a new PR :)

**Pull request merged**
