### PR TITLE
fix: enable multiplatform docker builds

### PR DESCRIPTION
**Pull request by tandy-1000**
This [should](https://github.com/docker/build-push-action/issues/302) fix it.
Can we test the change?

### CODE REVIEW

**Comment by tandy-1000** [comment]
I also just noticed that the `ci.yaml` checks ran even though this PR didn't make a change to the PHP or pipeline, using path filtering should be a quick win for saving credits :)

**Comment by tchapi** [comment]
Hi there
I don't think this is what is proposed in the associated issue. Look at https://github.com/cnorick/ha-auto-guest-login/pull/11 for instance

It's in the [doc](https://docs.docker.com/build/ci/github-actions/multi-platform/), too. We can use  `platforms`, but QEMU and buildx must be included beforehand

**Comment by tchapi** [comment]
> I also just noticed that the `ci.yaml` checks ran even though this PR didn't make a change to the PHP or pipeline, using path filtering should be a quick win for saving credits :)

You can rebase on `master` for this, it should be fixed, thanks for the hint!

**Comment by tandy-1000** [comment]
Ah, that's helpful, thank you!
Should be able to squash and merge now!

**Comment by tchapi** [comment]
Great; it worked: https://github.com/tchapi/davis/pkgs/container/davis/78658469?tag=edge

**Pull request merged**
