### PR TITLE
Fix: Change remaining blob columns to text

### PR DESCRIPTION
**Pull request by tchapi**
Following https://github.com/tchapi/davis/issues/110

### CODE REVIEW

**Comment by de-es** [comment]
Unfortunately is using TEXT in `carddata` from the `cards` table insufficient for my data. I got some images exceeding the TEXT with `Data too long`.

**Comment by tchapi** [comment]
> Unfortunately is using TEXT in carddata from the cards table insufficient for my data. I got some images exceeding the TEXT with Data too long.

Ah, interesting point.`TEXT` on Postgres is of unlimited size, so I can bump the size to `16,777,215` for instance, and create a migration for MySQL (using `MEDIUMTEXT`) 

Would 16 MiB be a good size, in your opinion?

**Comment by de-es** [comment]
IMHO that would be more than enough. Thanks for considering.

**Comment by tchapi** [comment]
→ https://github.com/tchapi/davis/pull/127

**Pull request merged**
